---
AWSTemplateFormatVersion: 2010-09-09
Description: Octank Hollywood SaaS Backend Tenant Registration Service
Parameters:
  BackendStackBucket:
    Description: The S3 bucket with Octank Hollywood resources
    Type: String
  ArtifactBucket:
    Description: The S3 bucket for CodeBuild to store built artifacts
    Type: String
  CodeBuildRoleArn:
    Description: The CodeBuild IAM role ARN
    Type: String
  CodePipelineRoleArn:
    Description: The CodePipeline IAM role ARN
    Type: String
  CloudWatchEventRoleArn:
    Description: The CloudWatch Event IAM role ARN
    Type: String
  LambdaCodeBuildStartBuildArn:
    Description: The Lambda function ARN to start a CodeBuild project
    Type: String
  LambdaClearEcrImagesArn:
    Description: The Lambda function ARN to delete the ECR images
    Type: String
  VPC:
    Description: The SaaS Octank Hollywood VPC
    Type: String
  ALBListener:
    Description: The HTTP listener on the load balancer for ECS
    Type: String
  ECSCluster:
    Description: ECS Cluster to run the ECS service in
    Type: String
  ServiceUrl:
    Description: API Gateway endpoint URL in front of the microservices
    Type: String
  ECSSecurityGroup:
    Description: Security Group for ECS
    Type: String
  ECSServiceRole:
    Description: ECS service-linked role
    Type: String
  SubnetPrivateA:
    Description: Subnet for ECS service to place tasks in
    Type: String
  SubnetPrivateB:
    Description: Subnet for ECS service to place tasks in
    Type: String
Resources:
  ECSRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: saas-demo/tenant-registration
  InvokeClearEcrRepoImages:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref LambdaClearEcrImagesArn
      Repository: !Ref ECSRepository
  CodeBuildLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/codebuild/saas-demo-registration-svc'
      RetentionInDays: 7
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: saas-demo-registration-svc
      Tags:
        - Key: Name
          Value: saas-demo-registration-svc
      ServiceRole: !Ref CodeBuildRoleArn
      TimeoutInMinutes: 10
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucket
        Path: '/'
        Name: tenant-registration
        Packaging: ZIP
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECSRepository}
          - Name: SAAS_BACKEND_BUCKET
            Value: !Ref BackendStackBucket
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - aws s3 cp --recursive s3://$SAAS_BACKEND_BUCKET/source/tenant-registration ./tenant-registration
                - aws s3 cp --recursive s3://$SAAS_BACKEND_BUCKET/source/shared-modules ./tenant-registration/shared-modules
                - $(aws ecr get-login --no-include-email)
            build:
              commands:
                - cd tenant-registration
                - docker image build -t saas-demo/tenant-registration -f Dockerfile .
                - docker tag saas-demo/tenant-registration:latest ${REPOSITORY_URI}:latest
                - cd ../
            post_build:
              commands:
                - docker push "${REPOSITORY_URI}:latest"
                - printf '[{"name":"tenant-registration","imageUri":"%s"}]' "${REPOSITORY_URI}:latest" > imagedefinitions.json
          artifacts:
            files: imagedefinitions.json
            discard-paths: yes
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: ECSService
    Properties:
      Name: saas-demo-registration-svc
      RoleArn: !Ref CodePipelineRoleArn
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Ref ArtifactBucket
                S3ObjectKey: tenant-registration
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: imgdef
        - Name: Deploy
          Actions:
            - Name: PreDeployAction
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Provider: Lambda
                Version: 1
              RunOrder: 1
              Configuration:
                FunctionName: !Sub saas-demo-update-ecs-${AWS::Region}
                UserParameters: !Sub '{"cluster":"${ECSCluster}","service":"${ECSService}","desiredCount":1}'
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              RunOrder: 2
              Configuration:
                ClusterName: !Ref ECSCluster
                ServiceName: saas-demo-registration-svc
                FileName: imagedefinitions.json
              InputArtifacts:
                - Name: imgdef
  CloudWatchEventRuleForCodePipeline:
    DependsOn: CodePipeline
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            - CopyObject
            - PutObject
            - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - !Ref ArtifactBucket
            key:
              - tenant-registration
      Targets:
        - Arn: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipeline}
          RoleArn: !Ref CloudWatchEventRoleArn
          Id: saas-demo-registration-svc
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: ECSLogGroup
    Properties:
      RoleName: saas-demo-registration-svc-exec-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: saas-demo-registration-svc-exec-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECSRepository}
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:DescribeLogStreams
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*
  ECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/ecs/saas-demo-registration-svc'
      RetentionInDays: 7
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: saas-demo-registration-svc-task-role
      Path: '/'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - ECSTaskExecutionRole
      - ECSTaskRole
    Properties:
      Family: saas-demo-registration-svc
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      Memory: 1024
      Cpu: 512
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: tenant-registration
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECSRepository}:latest
          PortMappings:
            - ContainerPort: 3004
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref ECSLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          Environment:
            - Name: AWS_REGION
              Value: !Ref AWS::Region
              # Shared config module sets the account id that the User Manager needs when creating IAM polices
            - Name: AWS_ACCOUNT_ID
              Value: !Ref AWS::AccountId
            - Name: SERVICE_URL
              Value: !Ref ServiceUrl
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: saas-demo-registration-svc
      HealthCheckProtocol: HTTP
      HealthCheckPath: '/reg/health'
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 10
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPC
  ALBRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      Conditions:
        - Field: path-pattern
          Values: ['/reg*']
      ListenerArn: !Ref ALBListener
      Priority: 4
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSTaskDefinition
      - ALBRule
    Properties:
      ServiceName: saas-demo-registration-svc
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 0
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref ECSSecurityGroup
          Subnets:
            - !Ref SubnetPrivateA
            - !Ref SubnetPrivateB
      LoadBalancers:
        - ContainerName: tenant-registration
          ContainerPort: 3004
          TargetGroupArn: !Ref ALBTargetGroup
  InvokeLambdaCodeBuildStartBuild:
    Type: Custom::CustomResource
    DependsOn:
      - CodeBuildProject
      - CodePipeline
      - CloudWatchEventRuleForCodePipeline
    Properties:
      ServiceToken: !Ref LambdaCodeBuildStartBuildArn
      Project: saas-demo-registration-svc
...